@echo OFF

SET /P TAPE_DIRECTORY=Tape directory of tapes:

SET /P DATE=Tape file event date(yyyyMM):
SET OUTFOLDER=E:\OptionData\NxCoreData
SET SUFFIX=.DO.nxc
SET /A DAY=0

:day
SET /A DAY=%DAY%+1
IF %DAY% LEQ 31 (
	IF %DAY% LSS 10 (
::		ECHO NxCoreReader %TAPE_DIRECTORY%\%DATE%0%DAY%%SUFFIX% %OUTFOLDER%\%DATE%0%DAY%%SUFFIX%.trade
::		CALL NxCoreReader %TAPE_DIRECTORY%\%DATE%0%DAY%%SUFFIX% %OUTFOLDER%\%DATE%0%DAY%%SUFFIX%.trade
		ECHO NxCoreReader %TAPE_DIRECTORY%\%DATE%0%DAY%%SUFFIX% -r
		CALL NxCoreReader %TAPE_DIRECTORY%\%DATE%0%DAY%%SUFFIX% -r
	) ELSE (
::		ECHO NxCoreReader %TAPE_DIRECTORY%\%DATE%%DAY%%SUFFIX% %OUTFOLDER%\%DATE%%DAY%%SUFFIX%.trade
::		CALL NxCoreReader %TAPE_DIRECTORY%\%DATE%%DAY%%SUFFIX% %OUTFOLDER%\%DATE%%DAY%%SUFFIX%.trade
		ECHO NxCoreReader %TAPE_DIRECTORY%\%DATE%%DAY%%SUFFIX% -r
		CALL NxCoreReader %TAPE_DIRECTORY%\%DATE%%DAY%%SUFFIX% -r
	)
	GOTO day
)

SET /A DATE=%DATE%+1
SET /A DAY=0
IF %DATE% LSS 201802 (
	GOTO day
)
pause