@echo OFF

SET OUTFOLDER=%2
SET PREFIX=%1
SET SUFFIX=.DO.nxc
SET /A DAY=0

:start
SET /A DAY=%DAY%+1
IF %DAY% LEQ 31 (
	IF %DAY% LSS 10 (
		ECHO NxCoreReader %PREFIX%0%DAY%%SUFFIX% %OUTFOLDER%\%PREFIX%0%DAY%%SUFFIX%.trade
		CALL NxCoreReader %PREFIX%0%DAY%%SUFFIX% %OUTFOLDER%\%PREFIX%0%DAY%%SUFFIX%.trade
	) ELSE (
		ECHO NxCoreReader %PREFIX%%DAY%%SUFFIX% %OUTFOLDER%\%PREFIX%0%DAY%%SUFFIX%.trade
		CALL NxCoreReader %PREFIX%%DAY%%SUFFIX% %OUTFOLDER%\%PREFIX%0%DAY%%SUFFIX%.trade		
	)
	GOTO start
)
pause